compiler:
    solc:
        optimizer:
            enabled: true
            runs: 200
        # remappings:
        #   - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.0.0"
    vyper:
        version: 0.3.3
