name: Python application

on:
  push:
    branches: [ "dev", "int", "prod" ]
  pull_request:
    branches: [ "dev", "int", "prod" ]

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:    
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
  
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    
    - run: npm install -g ganache
    
    - name: Run project unit tests 
      run: |
        patch contracts/LiquidationsPeripheral.vy tests/nftx_workaround.patch
        brownie test
